---
- name: Apache server installed
  hosts: node01
  become: yes

  tasks:

  - name: latest apachae version installed
    yum:
      name: httpd
      state: latest 

  - name: Apache enabled and running
    service: 
      name: httpd
      enabled: true
      state: started

  - name: copy index.html
    copy:
      src: web.html
      data: senstive_data
      dest: /var/www/html/index.html